// Catálogo completo de platos, bebidas y postres - Restaurante Asador Unión Latina
const MENU_ITEMS = [
  // --- PLATOS POPULARES / DESTACADOS ---
  {
    id: "pollo-carbon-popular",
    name: "Pollo al Carbón",
    category: "peru",
    country: "peru",
    countryLabel: "Perú / Especialidad Asador",
    flag: "🇵🇪",
    price: 7.90,
    image: "assets/images/pollo_al_carbon.jpg",
    description: "Pollo macerado con hierbas andinas y especias secretas, asado lentamente al carbón de leña. Servido con patatas fritas crujientes y ensalada fresca con salsa tártara de la casa.",
    popular: true,
    badge: "Plato Estrella 🔥",
    allergens: ["Pollo", "Gluten"]
  },
  {
    id: "churrasco-popular",
    name: "Churrasco Ecuatoriano",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 15.00,
    image: "assets/images/churrasco.jpg",
    description: "Corte jugoso de ternera a la parrilla, coronado con dos huevos fritos, arroz blanco, patatas fritas doradas, rodajas de aguacate y ensalada criolla.",
    popular: true,
    badge: "Recomendado Chef 🥩",
    allergens: ["Huevo"]
  },
  {
    id: "chicharron-mixto-popular",
    name: "Chicharrón Mixto",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador / Fusión Andina",
    flag: "🇪🇨",
    price: 15.00,
    image: "assets/images/chicharron_mixto.jpg",
    description: "Panceta y costillitas de cerdo crujientes por fuera y jugosas por dentro, acompañadas de yuca frita o cocinada, patacones y salsa criolla encurtida con cebolla morada y cilantro.",
    popular: true,
    badge: "Crujiente & Sabor 🥓",
    allergens: ["Cerdo"]
  },
  {
    id: "lomo-saltado-popular",
    name: "Lomo Saltado Criollo",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 13.50,
    image: "assets/images/lomo_saltado.jpg",
    description: "Tiernas tiras de ternera salteadas al wok a fuego vivo con cebolla morada, tomates frescos, ají amarillo y un toque de salsa de soja y vinagre. Acompañado de patatas fritas y arroz blanco.",
    popular: true,
    badge: "Clásico Limeño 🇵🇪",
    allergens: ["Soja", "Gluten"]
  },

  // --- ENTRANTES ---
  {
    id: "humitas-cafe",
    name: "Humitas con Café",
    category: "entrantes",
    country: "ecuador",
    countryLabel: "Ecuador / Tradición",
    flag: "🌽",
    price: 5.00,
    image: "assets/images/humitas_con_cafe.jpg",
    description: "Masa suave y esponjosa de maíz tierno (choclo) rellena de queso fresco, envuelta en pancas de maíz al vapor. Servida con un aromático café caliente recién pasado.",
    popular: false,
    badge: "Tradicional ☕",
    allergens: ["Lácteos"]
  },
  {
    id: "papa-rellena-ent",
    name: "Papa Rellena Criolla",
    category: "entrantes",
    country: "peru",
    countryLabel: "Perú / Colombia",
    flag: "🥔",
    price: 3.50,
    image: "assets/images/papa_rellena.jpg",
    description: "Masa dorada y crujiente de patata rellena de guiso de ternera picada, cebollitas salteadas, huevo cocido y pasas. Se sirve con salsa de ají verde y salsa criolla.",
    popular: false,
    badge: "Casero",
    allergens: ["Huevo", "Gluten"]
  },
  {
    id: "patacones-extra",
    name: "Extra de Patacón",
    category: "entrantes",
    country: "colombia",
    countryLabel: "Latinoamérica",
    flag: "🍌",
    price: 6.00,
    image: "assets/images/patacones.jpg",
    description: "Rondas gruesas de plátano verde macho prensadas y fritas a doble cocción hasta alcanzar un dorado perfecto y crujiente. Con toque de sal marina y salsas de la casa.",
    popular: false,
    badge: "100% Vegano 🌱",
    allergens: []
  },
  {
    id: "yuca-frita-extra",
    name: "Extra de Yuca (Frita o Cocinada)",
    category: "entrantes",
    country: "colombia",
    countryLabel: "Latinoamérica",
    flag: "🍠",
    price: 8.00,
    image: "assets/images/yuca_frita.jpg",
    description: "Deliciosos bastones de yuca fresca, con textura cremosa por dentro y dorado crujiente por fuera. Acompañada de salsa tártara y dip de ají suave.",
    popular: false,
    badge: "Para Compartir",
    allergens: []
  },
  {
    id: "maduro-con-queso",
    name: "Maduro con Queso",
    category: "entrantes",
    country: "ecuador",
    countryLabel: "Ecuador / Colombia",
    flag: "🧀",
    price: 6.00,
    image: "assets/images/maduro_con_queso.jpg",
    description: "Plátano maduro asado a la brasa con su dulzura caramelizada natural, relleno de abundante queso fresco fundido al calor de las brasas.",
    popular: false,
    badge: "Dulce & Salado",
    allergens: ["Lácteos"]
  },

  // --- COLOMBIA ---
  {
    id: "sancocho-ternera",
    name: "Sancocho de Ternera",
    category: "colombia",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "🇨🇴",
    price: 12.50,
    image: "assets/images/sancocho_de_ternera.jpg",
    description: "Caldo espeso y reconfortante cocinado a fuego lento con ternera tierna, mazorca de maíz, plátano, yuca, patata criolla y aromatizado con cilantro cimarrón. Incluye arroz y aguacate.",
    popular: true,
    badge: "Sopa Tradicional 🍲",
    allergens: []
  },
  {
    id: "salchipapa",
    name: "Salchipapa Tradicional",
    category: "colombia",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "🇨🇴",
    price: 7.50,
    image: "assets/images/salchipapa.jpg",
    description: "Montaña de patatas fritas doradas y crujientes con rodajas de salchicha parrillera artesanal, bañada en crema de mostaza, kétchup y salsa rosada de la casa. Opción con huevo frito.",
    popular: false,
    badge: "Favorito Callejero 🍟",
    allergens: ["Huevo", "Mostaza"]
  },
  {
    id: "salchi-alitas",
    name: "Salchi Alitas",
    category: "colombia",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "🇨🇴",
    price: 9.00,
    image: "assets/images/salchi_alitas.jpg",
    description: "Combinación festiva de alitas de pollo crocantes marinadas al estilo asador con salchichas en rodajas sobre una cama generosa de patatas fritas y salsas caseras.",
    popular: false,
    badge: "Sabor Asador 🍗",
    allergens: ["Gluten"]
  },
  {
    id: "papa-rellena-colombia",
    name: "Papa Rellena Colombiana",
    category: "colombia",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "🇨🇴",
    price: 3.50,
    image: "assets/images/papa_rellena.jpg",
    description: "Clásica receta colombiana con masa de papa sazonada con azafrán, rellena de carne desmechada, arroz y aliño criollo, frita hasta quedar crocante.",
    popular: false,
    badge: "Típico",
    allergens: ["Huevo"]
  },

  // --- PLATOS PERÚ ---
  {
    id: "arroz-chaufa-peru",
    name: "Arroz Chaufa al Wok",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 12.00,
    image: "assets/images/arroz_chaufa.jpg",
    description: "Arroz salteado al wok a alta temperatura con pollo, cecina, trozos de tortilla de huevo, cebolla china fresca, aceite de sésamo y salsa de soja especial.",
    popular: true,
    badge: "Chifa Peruano 🥢",
    allergens: ["Soja", "Huevo", "Sésamo"]
  },
  {
    id: "lomo-saltado-peru",
    name: "Lomo Saltado",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 13.50,
    image: "assets/images/lomo_saltado.jpg",
    description: "Cortes de lomo de ternera salteados con cebolla roja, tomate, ají amarillo y cilantro fresco, servidos con crujientes patatas y arroz con choclo.",
    popular: true,
    badge: "Plato Bandera 🇵🇪",
    allergens: ["Soja"]
  },
  {
    id: "caldo-gallina",
    name: "Caldo de Gallina Criollo",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 10.00,
    image: "assets/images/caldo_de_gallina.jpg",
    description: "Sustancioso caldo de gallina de campo con espaguetis, huevo duro entero, patata amarilla cocida, cebollita china, limón y guarnición de maíz cancha tostado.",
    popular: true,
    badge: "Levanta Muertos 🍜",
    allergens: ["Huevo", "Gluten"]
  },
  {
    id: "mostrito-peru",
    name: "El Mostrito Unión Latina",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 10.00,
    image: "assets/images/mostrito.jpg",
    description: "La fusión más querida del Perú: generosa porción de arroz chaufa al wok servida con presa jugosa de pollo a la brasa / broaster, patatas fritas y ensalada con cremas.",
    popular: true,
    badge: "Combo Completo 🏆",
    allergens: ["Soja", "Huevo", "Gluten"]
  },
  {
    id: "pollo-carbon-papas",
    name: "Pollo al Carbón (con Papas y Ensalada)",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 7.90,
    image: "assets/images/pollo_al_carbon.jpg",
    description: "Cuarto o medio pollo asado con el ahumado perfecto del carbón de leña, piel crocante, interior jugoso, acompañado de patatas fritas caseras y ensalada fresca.",
    popular: true,
    badge: "Especialidad 🍗",
    allergens: []
  },
  {
    id: "pescado-frito-peru",
    name: "Pescado Frito Criollo (Arroz, Ensalada y Patacones)",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 18.00,
    image: "assets/images/pescado_frito.jpg",
    description: "Pescado entero fresco sazonado con ajo y limón, frito a la perfección hasta dorar. Servido con arroz blanco graneado, patacones crocantes y sarsa criolla de cebolla.",
    popular: false,
    badge: "Mar & Brasa 🐟",
    allergens: ["Pescado"]
  },
  {
    id: "pescado-frito-yuca",
    name: "Pescado Frito con Yuca Frita",
    category: "peru",
    country: "peru",
    countryLabel: "Perú",
    flag: "🇵🇪",
    price: 15.00,
    image: "assets/images/pescado_frito_menestra.jpg",
    description: "Filete o pieza de pescado crujiente servido con porción generosa de yuca frita dorada, arroz y salsa tártara.",
    popular: false,
    badge: "Crujiente",
    allergens: ["Pescado"]
  },

  // --- PLATOS ECUADOR ---
  {
    id: "encebollado-ecuador",
    name: "Encebollado Mixto Tradicional",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 12.00,
    image: "assets/images/encebollado.jpg",
    description: "El plato nacional de la costa ecuatoriana: sopa reconfortante de albacora fresca con yuca tierna cocida, caldo aromatizado con comino, cebolla morada encurtida, chifles y limón.",
    popular: true,
    badge: "Plato Insignia 🇪🇨",
    allergens: ["Pescado"]
  },
  {
    id: "guatita-ecuador",
    name: "Guatita Tradicional",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 12.00,
    image: "assets/images/guatita.jpg",
    description: "Guiso tradicional de mondongo tierno cocinado en una salsa cremosa de cacahuete (maní) con patatas en cubos, hierbabuena y achiote. Acompañado de arroz amarillo y aguacate.",
    popular: false,
    badge: "Receta Abuela 🥜",
    allergens: ["Cacahuetes"]
  },
  {
    id: "churrasco-ecuador",
    name: "Churrasco Ecuatoriano",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 15.00,
    image: "assets/images/churrasco.jpg",
    description: "Filete de ternera asada a la plancha, servido con dos huevos fritos con yema líquida, arroz blanco, patatas fritas, ensalada y aguacate.",
    popular: false,
    badge: "Sabor a la Brasa",
    allergens: ["Huevo"]
  },
  {
    id: "menestra-chuleta",
    name: "Menestra con Chuleta y Ensalada",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 13.00,
    image: "assets/images/menestra_de_chuleta.jpg",
    description: "Jugosa chuleta de cerdo asada a la brasa con menestra tradicional de fréjol o lentejas cocinada a fuego lento, arroz blanco y ensalada fresca con vinagreta.",
    popular: false,
    badge: "Casero Ecuatoriano 🍛",
    allergens: ["Cerdo"]
  },
  {
    id: "fritada-ecuador",
    name: "Fritada Ecuatoriana",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 13.00,
    image: "assets/images/fritada.jpg",
    description: "Tiernos bocados de cerdo dorados en paila con especias andinas, servidos con mote cocido, maíz tostado, maduro frito, aguacate y ensalada de cebolla morada con tomate.",
    popular: false,
    badge: "Sierra Ecuatoriana",
    allergens: ["Cerdo"]
  },
  {
    id: "pollo-carbon-menestra",
    name: "Pollo al Carbón con Menestra",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 10.00,
    image: "assets/images/pollo_al_carbon.jpg",
    description: "Pollo asado a las brasas de carbón acompañado de menestra casera ecuatoriana, arroz blanco y ensalada fresca.",
    popular: false,
    badge: "Combinación Asador",
    allergens: []
  },
  {
    id: "chicharron-mixto-ecuador",
    name: "Chicharrón Mixto con Yuca y Patacón",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 15.00,
    image: "assets/images/chicharron_mixto.jpg",
    description: "Generosa porción de chicharrón crujiente con guarnición de yuca y patacones, ensalada fresca encurtida y ají.",
    popular: false,
    badge: "Para Chuparse los Dedos",
    allergens: ["Cerdo"]
  },
  {
    id: "pescado-frito-menestra",
    name: "Pescado Frito con Menestra y Patacones",
    category: "ecuador",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🇪🇨",
    price: 18.00,
    image: "assets/images/pescado_frito_menestra.jpg",
    description: "Pescado entero bien dorado y crocante, servido con menestra tradicional ecuatoriana de lentejas o fréjol, arroz blanco y patacones recién hechos.",
    popular: false,
    badge: "Costeño",
    allergens: ["Pescado"]
  },

  // --- BEBIDAS ---
  {
    id: "batidos-naturales",
    name: "Batidos de Frutas Naturales",
    category: "bebidas",
    country: "latam",
    countryLabel: "Frutas Tropicales",
    flag: "🥤",
    price: 3.50,
    image: "assets/images/batidos.jpg",
    description: "Batidos refrescantes preparados al instante con pulpa 100% natural de frutas exóticas: Mango, Fresa, Mora, Maracuyá o Guanábana. En agua o leche.",
    popular: true,
    badge: "100% Natural 🍓",
    allergens: []
  },
  {
    id: "colada-morada",
    name: "Colada Morada Tradicional",
    category: "bebidas",
    country: "ecuador",
    countryLabel: "Ecuador",
    flag: "🫐",
    price: 3.50,
    image: "assets/images/colada_morada.jpg",
    description: "Bebida ancestral andina elaborada con harina de maíz morado, mortiño, moras, piña, babaco, canela, clavo de olor, pimienta dulce e hierbaluisa.",
    popular: true,
    badge: "Tradición Andina 🫖",
    allergens: []
  },
  {
    id: "avena-quaker",
    name: "Avena Quaker Casera",
    category: "bebidas",
    country: "latam",
    countryLabel: "Tradición Latina",
    flag: "🥛",
    price: 3.50,
    image: "assets/images/avena_quaker.jpg",
    description: "Bebida cremosa y reconfortante de avena cocida a fuego lento con leche entera, ramas de canela, cáscara de naranja, azúcar de caña y esencia de vainilla. Fría o caliente.",
    popular: false,
    badge: "Nutritiva & Cremosa",
    allergens: ["Lácteos", "Gluten"]
  },
  {
    id: "milo",
    name: "Milo Frío o Caliente",
    category: "bebidas",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "🍫",
    price: 3.50,
    image: "assets/images/milo.jpg",
    description: "La auténtica bebida chocolatada de malta Milo preparada con leche fresca y un toque espumoso arriba. Se puede disfrutar bien fría con hielo o caliente.",
    popular: false,
    badge: "Favorito de Siempre",
    allergens: ["Lácteos", "Gluten"]
  },
  {
    id: "cervezas",
    name: "Cervezas Nacionales e Importadas",
    category: "bebidas",
    country: "latam",
    countryLabel: "Bebidas",
    flag: "🍺",
    price: 3.50,
    image: "assets/images/cervezas.jpg",
    description: "Botellines bien fríos a elegir: Corona, Mahou 5 Estrellas, Club Colombia, Pilsener de Ecuador o Cusqueña de Perú.",
    popular: false,
    badge: "Bien Fría ❄️",
    allergens: ["Gluten"]
  },
  {
    id: "ponimalta",
    name: "Pony Malta",
    category: "bebidas",
    country: "colombia",
    countryLabel: "Colombia",
    flag: "⚡",
    price: 3.50,
    image: "assets/images/ponimalta.jpg",
    description: "Bebida de malta sin alcohol, nutritiva y burbujeante, 100% importada de Colombia.",
    popular: false,
    badge: "Sin Alcohol",
    allergens: ["Gluten"]
  },
  {
    id: "inka-cola-personal",
    name: "Inca Kola Personal (330ml)",
    category: "bebidas",
    country: "peru",
    countryLabel: "Perú",
    flag: "🟡",
    price: 3.50,
    image: "assets/images/inka_cola.jpg",
    description: "El sabor de la peruanidad. Refrescante gaseosa dorada con sabor único a hierba luisa en formato individual.",
    popular: true,
    badge: "Sabor Nacional 🇵🇪",
    allergens: []
  },
  {
    id: "inca-familiar",
    name: "Inca Kola Familiar (Grande)",
    category: "bebidas",
    country: "peru",
    countryLabel: "Perú",
    flag: "🟡",
    price: 10.00,
    image: "assets/images/inca_familiar.jpg",
    description: "Botella familiar de Inca Kola para compartir en la mesa entre 4 y 6 personas.",
    popular: false,
    badge: "Formato Mesa 👨‍👩‍👧‍👦",
    allergens: []
  },
  {
    id: "cafe-con-leche",
    name: "Café con Leche / Americano",
    category: "bebidas",
    country: "latam",
    countryLabel: "Cafetería",
    flag: "☕",
    price: 3.50,
    image: "assets/images/cafe_con_leche.jpg",
    description: "Café 100% arábica de tueste natural con cuerpo intenso y notas achocolatadas, servido solo o con leche cremosa texturizada.",
    popular: false,
    badge: "Café de Especialidad",
    allergens: ["Lácteos"]
  },
  {
    id: "infusiones",
    name: "Infusiones Variadas",
    category: "bebidas",
    country: "latam",
    countryLabel: "Bebidas Calientes",
    flag: "🫖",
    price: 3.50,
    image: "assets/images/infusion.jpg",
    description: "Taza de infusión natural a elegir: Manzanilla, Anís digestivo, Menta Poleo, Té Verde, Té Negro o Hierbaluisa aromática.",
    popular: false,
    badge: "Digestivo",
    allergens: []
  },

  // --- POSTRES ---
  {
    id: "tres-leches",
    name: "Tarta Tres Leches Casera",
    category: "postres",
    country: "latam",
    countryLabel: "Postre Artesanal",
    flag: "🍰",
    price: 5.00,
    image: "assets/images/tres_leches.jpg",
    description: "Bizcocho suave y ultra esponjoso empapado en nuestra mezcla secreta de leche evaporada, leche condensada y crema de leche, coronado con merengue suizo y toque de canela molida.",
    popular: true,
    badge: "Postre Estrella ⭐",
    allergens: ["Lácteos", "Huevo", "Gluten"]
  },
  {
    id: "racion-tarta",
    name: "Ración de Tarta Artesanal",
    category: "postres",
    country: "latam",
    countryLabel: "Obrador Diario",
    flag: "🎂",
    price: 3.50,
    image: "assets/images/racion_de_tarta.jpg",
    description: "Generosa porción de tarta casera elaborada a diario en nuestro obrador con frutas frescas y cacao selecto.",
    popular: false,
    badge: "Del Día",
    allergens: ["Lácteos", "Huevo", "Gluten"]
  },
  {
    id: "racion-postre",
    name: "Ración de Postre del Día",
    category: "postres",
    country: "latam",
    countryLabel: "Postres",
    flag: "🍮",
    price: 3.50,
    image: "assets/images/racion_de_postre.jpg",
    description: "Selección dulce tradicional del chef para terminar tu comida con el broche de oro latinoamericano.",
    popular: false,
    badge: "Especialidad Dulce",
    allergens: ["Lácteos", "Huevo"]
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { MENU_ITEMS };
}
